### ISSUE TITLE
problem with some fonts

### ISSUE THREAD

**Issue by fa1rid** [safina3d/c4d-zarabic#1]
I tried a font called "Dubai" and some of the letters appeared as square or rectangle.
Why like that and what's the solution?

**Comment by safina3d** [comment]
Hi, can you post a screenshot ? do you use Tachkil in your text ? I already have an idea about this problem but I want to be sure. Thank you

**Comment by safina3d** [comment]
Done ! zArabic 1.3.6

**Comment by fa1rid** [comment]
Sorry for the delay. I wanted to send you a screenshot but I see you already fixed the problem :). Thanks a lot. I have tested it now and the problem is fixed.
